version: '3.6'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        working_dir: /var/www/html
        ports:
            - '8090:80'
        volumes:
            - ./:/var/www/html
            - ~/.ssh:/root/.ssh
        networks:
            - default
            - webhelp-kyc-docker_default

volumes:
    postgresql-volume:

networks:
    webhelp-kyc-docker_default:
        external: true
