version: '3.6'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        working_dir: /var/www/html
        ports:
            - '8090:80'
        volumes:
            - ./:/var/www/html
            - ~/.ssh:/root/.ssh
            - ../internal_api_bundle:/var/www/internal_api_bundle
        networks:
            - default
            - webhelp-kyc-docker_default
    bo_redis:
        image: redis:latest
        volumes: [ 'redis:/data' ]

volumes:
    postgresql-volume:
    redis:

networks:
    webhelp-kyc-docker_default:
        external: true
