version: '3.6'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /var/www/html
    ports:
      - '8090:80'
    volumes:
      - ./:/var/www/html
      - ~/.ssh:/root/.ssh
  bo_redis:
    image: redis:latest
    volumes: [ 'redis:/data' ]

volumes:
  postgresql-volume:
  redis:
