#!/usr/bin/env bash

grn=$'\e[1;32m'
red=$'\e[1;31m'
end=$'\e[0m'

echo "$grn Trying to run tests... $end";

docker-compose exec -T app php bin/phpunit

if [ $? -eq 0 ]
then
echo "$grn Tests ran SUCCESSFULLY! $end";
echo "$grn Pushing commits... $end";
else
echo "$red Tests FAILED! $end";
exit 1;
fi
