services:
  # default configuration for services in *this* file
  _defaults:
    public: true
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\Fetcher\FolderFetcher:
    public: true

  App\Facade\InternalApi\DocumentFacade:
    public: true

  App\Services\PersonService:
    public: true
